mvctest/mvctest/Models/Staff.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvctest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities1 : DbContext
    {
        public CinemaEntities1()
            : base("name=CinemaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Staff> Staff { get; set; }
    }
}

mvctest/mvctest/Models/Staff.Designer.cs
// 为模型“E:\practice\asp.net\.net framework(mvc)\mvctest\mvctest\Models\Staff.edmx”启用了 T4 代码生成。
// 要启用旧代码生成功能，请将“代码生成策略”设计器属性的值
// 更改为“旧的 ObjectContext”。当在设计器中打开该模型时，此属性会出现在
// “属性”窗口中。

// 如果没有生成任何上下文和实体类，可能是因为您创建了空模型但是
// 尚未选择要使用的实体框架版本。要为您的模型生成一个上下文类和实体
// 类，请在设计器中打开该模型，右键单击设计器图面，然后
// 选择“从数据库更新模型...”、“从模型生成数据库...”或“添加代码生成
// 项...”。

mvctest/mvctest/Models/Staff.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvctest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int S_id { get; set; }
        public string S_name { get; set; }
        public int S_age { get; set; }
        public string S_gender { get; set; }
        public string S_post { get; set; }
        public string S_department { get; set; }
    }
}

mvctest/mvctest/Models/Staff1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

mvctest/mvctest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvctest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

mvctest/mvctest/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvctest.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        IList<string> NewTitlelist = new List<string>();
        int count = new Random().Next(3,5);
        public ActionResult Index()
        {
            for (int i=0;i<count;i++) 
            {
                NewTitlelist.Add("真虾头");
                NewTitlelist.Add("纯鹿人");
                NewTitlelist.Add("真无语");
                NewTitlelist.Add("鸡你太美");
                NewTitlelist.Add("amagi");
            }
            return View(NewTitlelist);
        }
    }
}

mvctest/mvctest/Controllers/RouteDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvctest.Controllers
{
    public class RouteDemoController : Controller
    {
        // GET: RouteDemo
        public ActionResult Index()
        {
            return View();
        }

        public int Data(DateTime dt) 
        {
            return ( dt - DateTime.Now).Days;
        }
    }
}

mvctest/mvctest/Controllers/Show_StaffController.cs
using mvctest.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvctest.Controllers
{
    public class Show_StaffController : Controller
    {
        // GET: Show_Staff
        //查询员工信息
        public ActionResult StaffList()
        {
            IList<Staff> staff= null;
            using (CinemaEntities1 db = new CinemaEntities1()) 
            {
                staff=db.Staff.Select(s => s).ToList();
            }
                return View(staff);
        }
        //添加员工信息操作
        [HttpGet]
        public ActionResult AddStaff()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddStaff(Staff staff)
        {
            using (CinemaEntities1 db=new CinemaEntities1())
            {
                db.Staff.Add(staff);
                db.SaveChanges();
            }         
                return RedirectToAction("StaffList");
        }

        //更新员工信息
        [HttpGet]
        public ActionResult UpdateStaff(int id)
        {
            Staff staff = null;
            using (CinemaEntities1 db = new CinemaEntities1())
            {
                staff = db.Staff.Where(w => w.S_id==id).FirstOrDefault();
            }
            return View(staff);
        }
        [HttpPost]
        public ActionResult UpdateStaff(Staff staff)
        {
            using (CinemaEntities1 db = new CinemaEntities1()) 
            {
                var Editstu =db.Staff.Attach(staff);//编辑状态
                Editstu.S_name = staff.S_name;
                Editstu.S_age = staff.S_age;
                Editstu.S_gender = staff.S_gender;
                Editstu.S_post = staff.S_post;
                Editstu.S_department = staff.S_department;
                db.Entry(Editstu).Property(p => p.S_name).IsModified = true;
                db.Entry(Editstu).Property(p => p.S_age).IsModified = true;
                db.Entry(Editstu).Property(p => p.S_gender).IsModified = true;
                db.Entry(Editstu).Property(p => p.S_post).IsModified = true;
                db.Entry(Editstu).Property(p => p.S_department).IsModified = true;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                db.Configuration.ValidateOnSaveEnabled = true;
            }
            return RedirectToAction("StaffList");
        }

        //删除员工信息
        [HttpGet]
        public ActionResult DeleteStaff(int id)
        {
            Staff staff = null;
            using (CinemaEntities1 db = new CinemaEntities1())
            {
                staff = db.Staff.Where(w => w.S_id == id).FirstOrDefault();
                if (staff != null)
                {
                    db.Staff.Remove(staff);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("StaffList");
        }
        
    }
}

mvctest/mvctest/Controllers/ikunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvctest.Controllers
{
    public class ikunController : Controller
    {
        // GET: ikun
        public ActionResult Index()
        {
            return View();
        }
    }
}

mvctest/mvctest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

mvctest/mvctest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

mvctest/mvctest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

mvctest/mvctest/Views/News/Index.cshtml
@model IList<string>
@{
    ViewBag.Title = "新闻";
}

<ul>
    @{
        int i = 0;
        foreach (string s in Model)
        {
            
                if (i == 0)
                {
                    <li><h3 style="color:black"><a href="#">@s</a></h3></li>
                }
                else
                {
                    <li><h4><a href="#">@s</a></h4></li>
                }
                i++;
           

        }
    }
</ul>

mvctest/mvctest/Views/RouteDemo/Data.cshtml
@{
    ViewBag.Title = "Data";
}

<h2>Data</h2>

mvctest/mvctest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("新闻", "Index", "News")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

mvctest/mvctest/Views/Show_Staff/AddStaff.cshtml
@model mvctest.Models.Staff

@{
    ViewBag.Title = "员工信息添加";
}

<h2>员工信息</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.S_name,"姓名", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S_age, "年龄", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S_age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S_gender, "性别", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.S_gender,new List<SelectListItem>() { new SelectListItem() {Text="男",Selected=true },new SelectListItem() {Text="女"} }, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S_post, "岗位", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S_post, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_post, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S_department, "部门", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S_department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="创建" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mvctest/mvctest/Views/Show_Staff/DeleteStaff.cshtml
@model mvctest.Models.Staff

@{
    ViewBag.Title = "删除员工信息";
}




<div>
    <h4>员工信息</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.S_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.S_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.S_age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.S_age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.S_gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.S_gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.S_post)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.S_post)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.S_department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.S_department)
        </dd>
        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

mvctest/mvctest/Views/Show_Staff/StaffList.cshtml
@model IList<mvctest.Models.Staff> 
@{
    ViewBag.Title = "StaffList";
}
<table>
    <tr><td colspan="5" align="right">@Html.ActionLink("添加员工信息", "AddStaff", "Show_Staff")</td></tr>
    <tr><th height="40">ID</th><th>姓名</th><th>年龄</th><th>性别</th><th>岗位</th><th>部门</th></tr>
    @{
        foreach (mvctest.Models.Staff staffs in Model)
        {
            <tr>
                <td height="30">@staffs.S_id</td>
                <td height="30">@staffs.S_name</td>
                <td height="30">@staffs.S_age</td>
                <td height="30">@staffs.S_gender</td>
                <td height="30">@staffs.S_post</td>
                <td height="30">@staffs.S_department</td>
                <td>@Html.ActionLink("修改员工信息", "UpdateStaff", new { id = staffs.S_id })</td>
                <td>@Html.ActionLink("删除员工信息", "DeleteStaff", new { id = staffs.S_id })</td>
            </tr>
        }
    }
</table>

mvctest/mvctest/Views/Show_Staff/UpdateStaff.cshtml
@model mvctest.Models.Staff

@{
    ViewBag.Title = "更想员工信息";
}

<h2>员工信息</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.S_id)

        <div class="form-group">
            @Html.LabelFor(model => model.S_name,"姓名", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S_age, "年龄", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S_age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S_gender, "性别", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.S_gender,new List<SelectListItem> { new SelectListItem() {Text="男",Value="男",Selected=true },new SelectListItem() {Text="女",Value="女" } } , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S_post, "岗位", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S_post,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_post, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.S_department, "部门", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.S_department,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.S_department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mvctest/mvctest/Views/ikun/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>